- name: create ec2 and route 53
  connection: local
  hosts:  local
  vars:
    subnet_id: subnet-0b01fc2830d27fd2f
    sg_id: sg-0d5b9da6449c34cb3
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS python library
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - PyMySQL
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id  }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}" 
    register: ec2_info
  
  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ item.item }}:{{ item.private_ip_addresses.private_ip_address }}"
    loop: "{{ ec2_info.results }}"